spring:
  datasource:
    url: jdbc:postgresql://postgresql://postgres:wHQ1wiq2ybrgUVQKnA6q@containers-us-west-43.railway.app:7879/railway:7879/railway
    username: postgres
    password:  wHQ1wiq2ybrgUVQKnA6q

  sql:
    init:
      mode: always